name: Deploy pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v2  # Updated to existing version

      - uses: actions/setup-node@v2  # Updated to existing version
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Install slidev
        run: npm i -g @slidev/cli

      - name: Build
        run: slidev build --base slides.md

      # Replace with existing or custom actions
      # - uses: actions/configure-pages@v3

      # Replace with existing or custom actions
      # - uses: actions/upload-pages-artifact@v1
        # with:
        #   path: dist

      - name: Deploy
        id: deployment
        uses: actions/gh-pages@v3  # Updated to existing version
